// inputconstants.h
// Gregory Rosenblatt
// 5/11/05

#ifndef Starscape_Gui_Config_INPUTCONSTANTS_H_
#define Starscape_Gui_Config_INPUTCONSTANTS_H_

#include "SDL.h"

// converts to sdl input-constant identifiers
//#define STARSCAPE_CONCAT(X, Y)	X ## Y
//#define STARSCAPE_BUTTON(X)	STARSCAPE_CONCAT(SDL_BUTTON_, X)
//#define STARSCAPE_KEY(X)	STARSCAPE_CONCAT(SDL, X)
//#define STARSCAPE_KEYMOD(X)	STARSCAPE_CONCAT(KMOD_, X)

// mouse
#define STARSCAPE_BUTTON_LEFT		SDL_BUTTON_LEFT
#define STARSCAPE_BUTTON_MIDDLE		SDL_BUTTON_MIDDLE
#define STARSCAPE_BUTTON_RIGHT		SDL_BUTTON_RIGHT
#define STARSCAPE_BUTTON_WHEELUP	SDL_BUTTON_WHEELUP
#define STARSCAPE_BUTTON_WHEELDOWN	SDL_BUTTON_WHEELDOWN

// keyboard
#define STARSCAPE_KEY_ESCAPE	SDLK_ESCAPE
#define STARSCAPE_KEY_DELETE	SDLK_DELETE
#define STARSCAPE_KEY_BACKSPACE	SDLK_BACKSPACE

#define STARSCAPE_KEY_UP		SDLK_UP
#define STARSCAPE_KEY_DOWN		SDLK_DOWN
#define STARSCAPE_KEY_LEFT		SDLK_LEFT
#define STARSCAPE_KEY_RIGHT		SDLK_RIGHT
#define STARSCAPE_KEY_INSERT	SDLK_INSERT
#define STARSCAPE_KEY_HOME		SDLK_HOME
#define STARSCAPE_KEY_END		SDLK_END
#define STARSCAPE_KEY_PAGEUP	SDLK_PAGEUP
#define STARSCAPE_KEY_PAGEDOWN	SDLK_PAGEDOWN

#define STARSCAPE_KEY_SPACE		SDLK_SPACE
#define STARSCAPE_KEY_TAB		SDLK_TAB
#define STARSCAPE_KEY_RETURN	SDLK_RETURN
#define STARSCAPE_KEY_KP_ENTER	SDLK_KP_ENTER

#define STARSCAPE_KEY_NUMLOCK	SDLK_NUMLOCK
#define STARSCAPE_KEY_CAPSLOCK	SDLK_CAPSLOCK
#define STARSCAPE_KEY_SCROLLOCK	SDLK_SCROLLOCK
#define STARSCAPE_KEY_RSHIFT	SDLK_RSHIFT
#define STARSCAPE_KEY_LSHIFT	SDLK_LSHIFT
#define STARSCAPE_KEY_RCTRL		SDLK_RCTRL
#define STARSCAPE_KEY_LCTRL		SDLK_LCTRL
#define STARSCAPE_KEY_RALT		SDLK_RALT
#define STARSCAPE_KEY_LALT		SDLK_LALT

#define STARSCAPE_KEY_F1	SDLK_F1
#define STARSCAPE_KEY_F2	SDLK_F2
#define STARSCAPE_KEY_F3	SDLK_F3
#define STARSCAPE_KEY_F4	SDLK_F4
#define STARSCAPE_KEY_F5	SDLK_F5
#define STARSCAPE_KEY_F6	SDLK_F6
#define STARSCAPE_KEY_F7	SDLK_F7
#define STARSCAPE_KEY_F8	SDLK_F8
#define STARSCAPE_KEY_F9	SDLK_F9
#define STARSCAPE_KEY_F10	SDLK_F10
#define STARSCAPE_KEY_F11	SDLK_F11
#define STARSCAPE_KEY_F12	SDLK_F12
#define STARSCAPE_KEY_F13	SDLK_F13
#define STARSCAPE_KEY_F14	SDLK_F14
#define STARSCAPE_KEY_F15	SDLK_F15

#endif
